spring:
  datasource:
    url: jdbc:mysql://${LEAFSAVER_DB_HOST:localhost}:3306/${LEAFSAVER_DB:leaf_saver}
    username: ${LEAFSAVER_DB_USERNAME:sa}
    password: ${LEAFSAVER_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: NON_EMPTY

springdoc:
  swagger-ui:
    path: swagger-ui