spring:
  datasource:
    url: jdbc:h2:mem:leaf_saver
    driverClassname: org.h2.Driver
    username: ${LEAFSAVER_DB_USERNAME:sa}
    password: ${LEAFSAVER_DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
