package com.github.jaksa97.LeafSaver.stub;

import com.github.jaksa97.LeafSaver.model.entity.CureEntity;
import com.github.jaksa97.LeafSaver.model.entity.DiseaseEntity;
import com.github.jaksa97.LeafSaver.model.entity.DrugEntity;
import com.github.jaksa97.LeafSaver.model.entity.ProducerEntity;
import com.github.jaksa97.LeafSaver.repository.CureRepository;
import com.github.jaksa97.LeafSaver.repository.DiseaseRepository;
import com.github.jaksa97.LeafSaver.repository.DrugRepository;
import com.github.jaksa97.LeafSaver.repository.ProducerRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import java.util.Arrays;

@Component
@RequiredArgsConstructor
public class DbInitializer implements CommandLineRunner {

    private final DrugRepository _drugRepository;
    private final DiseaseRepository _diseaseRepository;
    private final ProducerRepository _producerRepository;

    private final CureRepository _cureRepository;

    @Override
    public void run(String... args) throws Exception {
//        initializeProducers();
//        initializeDiseases();
//        initializeDrugs();
//        initializeCures();
    }

    private void initializeCures() {
        CureEntity cure1 = new CureEntity(1, new DrugEntity(10, "Bravo 720 SC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(1, "Blueberry___healthy", "Blueberry healthy"), "Put 48 ml of medicament in 10 l of water");
        CureEntity cure2 = new CureEntity(2, new DrugEntity(5, "Acaritouch", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(2, "Apple___healthy", "Apple healthy"), "Put 49 ml of medicament in 5 l of water");
        CureEntity cure3 = new CureEntity(3, new DrugEntity(15, "Folio Gold 537.5 SC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(2, "Apple___healthy", "Apple healthy"), "Put 49 ml of medicament in 15 l of water");
        CureEntity cure4 = new CureEntity(4, new DrugEntity(19, "Belt™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(2, "Apple___healthy", "Apple healthy"), "Put 49 ml of medicament in 19 l of water");
        CureEntity cure5 = new CureEntity(5, new DrugEntity(30, "Pyridaben", new ProducerEntity(6, "Chaitra Agri Organics"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(3, "Apple___Black_rot", "Black rot"), "Put 50 ml of medicament in 30 l of water");
        CureEntity cure6 = new CureEntity(6, new DrugEntity(36, "Oxyfluorfen", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(3, "Apple___Black_rot", "Black rot"), "Put 50 ml of medicament in 36 l of water");
        CureEntity cure7 = new CureEntity(7, new DrugEntity(15, "Folio Gold 537.5 SC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(4, "Tomato___Tomato_mosaic_virus", "Mosaic virus"), "Put 51 ml of medicament in 15 l of water");
        CureEntity cure8 = new CureEntity(8, new DrugEntity(18, "Alion™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(4, "Tomato___Tomato_mosaic_virus", "Mosaic virus"), "Put 51 ml of medicament in 18 l of water");
        CureEntity cure9 = new CureEntity(9, new DrugEntity(22, "Prosaro™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(4, "Tomato___Tomato_mosaic_virus", "Mosaic virus"), "Put 51 ml of medicament in 22 l of water");
        CureEntity cure10 = new CureEntity(10, new DrugEntity(26, "Xpro™", new ProducerEntity(4, "DowDupont"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(4, "Tomato___Tomato_mosaic_virus", "Mosaic virus"), "Put 51 ml of medicament in 26 l of water");
        CureEntity cure11 = new CureEntity(11, new DrugEntity(6, "Benzofenap", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(5, "Apple___Cedar_apple_rust", "Cedar rust"), "Put 52 ml of medicament in 6 l of water");
        CureEntity cure12 = new CureEntity(12, new DrugEntity(29, "Methomyl", new ProducerEntity(5, "BASF"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(5, "Apple___Cedar_apple_rust", "Cedar rust"), "Put 52 ml of medicament in 29 l of water");
        CureEntity cure13 = new CureEntity(13, new DrugEntity(39, "Aldicarb sulfoxide", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(5, "Apple___Cedar_apple_rust", "Cedar rust"), "Put 52 ml of medicament in 39 l of water");
        CureEntity cure14 = new CureEntity(14, new DrugEntity(20, "Confidor™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(6, "Apple___Apple_scab", "Scab"), "Put 53 ml of medicament in 20 l of water");
        CureEntity cure15 = new CureEntity(15, new DrugEntity(21, "Harness™ Branded Herbicides", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(6, "Apple___Apple_scab", "Scab"), "Put 53 ml of medicament in 21 l of water");
        CureEntity cure16 = new CureEntity(16, new DrugEntity(33, "Dicofol", new ProducerEntity(7, "Camson Bio Technologies Ltd."), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(6, "Apple___Apple_scab", "Scab"), "Put 53 ml of medicament in 33 l of water");
        CureEntity cure17 = new CureEntity(17, new DrugEntity(26, "Xpro™", new ProducerEntity(4, "DowDupont"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(7, "Pepper,_bell___healthy", "Bell healthy"), "Put 54 ml of medicament in 26 l of water");
        CureEntity cure18 = new CureEntity(18, new DrugEntity(36, "Oxyfluorfen", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(7, "Pepper,_bell___healthy", "Bell healthy"), "Put 54 ml of medicament in 36 l of water");
        CureEntity cure19 = new CureEntity(19, new DrugEntity(3, "Flutianil", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(8, "Peach___healthy", "Peach healthy"), "Put 55 ml of medicament in 3 l of water");
        CureEntity cure20 = new CureEntity(20, new DrugEntity(4, "Kaligreen", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(8, "Peach___healthy", "Peach healthy"), "Put 55 ml of medicament in 4 l of water");
        CureEntity cure21 = new CureEntity(21, new DrugEntity(7, "Benfuresate", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(8, "Peach___healthy", "Peach healthy"), "Put 55 ml of medicament in 7 l of water");
        CureEntity cure22 = new CureEntity(22, new DrugEntity(6, "Benzofenap", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(9, "Tomato___Late_blight", "Late blight"), "Put 56 ml of medicament in 6 l of water");
        CureEntity cure23 = new CureEntity(23, new DrugEntity(10, "Bravo 720 SC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(9, "Tomato___Late_blight", "Late blight"), "Put 56 ml of medicament in 10 l of water");
        CureEntity cure24 = new CureEntity(24, new DrugEntity(31, "Imidacloprid", new ProducerEntity(6, "Chaitra Agri Organics"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(9, "Tomato___Late_blight", "Late blight"), "Put 56 ml of medicament in 31 l of water");
        CureEntity cure25 = new CureEntity(25, new DrugEntity(6, "Benzofenap", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(10, "Tomato___Septoria_leaf_spot", "Septoria leaf spot"), "Put 57 ml of medicament in 6 l of water");
        CureEntity cure26 = new CureEntity(26, new DrugEntity(18, "Alion™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(10,  "Tomato___Septoria_leaf_spot", "Septoria leaf spot"), "Put 57 ml of medicament in 18 l of water");
        CureEntity cure27 = new CureEntity(27, new DrugEntity(39, "Aldicarb sulfoxide", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests."), new DiseaseEntity(10,  "Tomato___Septoria_leaf_spot", "Septoria leaf spot"), "Put 57 ml of medicament in 39 l of water");


        _cureRepository.saveAll(Arrays.asList(cure1, cure2, cure3, cure4, cure5, cure6, cure7, cure8, cure9, cure10, cure11, cure12, cure13, cure14, cure15, cure16, cure17, cure18, cure19, cure20, cure21, cure22, cure23, cure24, cure25, cure26, cure27));
    }

    private void initializeDrugs() {
        DrugEntity drug1 = new DrugEntity(1, "Benfuracarb", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug2 = new DrugEntity(2, "Cyflumetofen", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug3 = new DrugEntity(3, "Flutianil", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug4 = new DrugEntity(4, "Kaligreen", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug5 = new DrugEntity(5, "Acaritouch", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug6 = new DrugEntity(6, "Benzofenap", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug7 = new DrugEntity(7, "Benfuresate", new ProducerEntity(1, "OAT Agrio"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug8 = new DrugEntity(8, "Amistar Extra 280 SC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug9 = new DrugEntity(9, "Artea 330 EC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug10 = new DrugEntity(10, "Bravo 720 SC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug11 = new DrugEntity(11, "Certicor 050 FS", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug12 = new DrugEntity(12, "Cherokee 487,5 SE", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug13 = new DrugEntity(13, "Chorus 50 WG", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug14 = new DrugEntity(14, "Dividend M 030 FS", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug15 = new DrugEntity(15, "Folio Gold 537.5 SC", new ProducerEntity(2, "Syngenta"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug16 = new DrugEntity(16, "Acceleron™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug17 = new DrugEntity(17, "Adengo™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug18 = new DrugEntity(18, "Alion™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug19 = new DrugEntity(19, "Belt™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug20 = new DrugEntity(20, "Confidor™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug21 = new DrugEntity(21, "Harness™ Branded Herbicides", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug22 = new DrugEntity(22, "Prosaro™", new ProducerEntity(3, "Bayer AG"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug23 = new DrugEntity(23, "Roundup™", new ProducerEntity(4, "DowDupont"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug24 = new DrugEntity(24, "Stratego™", new ProducerEntity(4, "DowDupont"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug25 = new DrugEntity(25, "Warrant™ Herbicide", new ProducerEntity(4, "DowDupont"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug26 = new DrugEntity(26, "Xpro™", new ProducerEntity(4, "DowDupont"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug27 = new DrugEntity(27, "Acephate", new ProducerEntity(5, "BASF"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug28 = new DrugEntity(28, "Dichlorvos", new ProducerEntity(5, "BASF"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug29 = new DrugEntity(29, "Methomyl", new ProducerEntity(5, "BASF"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug30 = new DrugEntity(30, "Pyridaben", new ProducerEntity(6, "Chaitra Agri Organics"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug31 = new DrugEntity(31, "Imidacloprid", new ProducerEntity(6, "Chaitra Agri Organics"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug32 = new DrugEntity(32, "Esfenvalerate", new ProducerEntity(6, "Chaitra Agri Organics"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug33 = new DrugEntity(33, "Dicofol", new ProducerEntity(7, "Camson Bio Technologies Ltd."), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug34 = new DrugEntity(34, "Diflubenzuron", new ProducerEntity(7, "Camson Bio Technologies Ltd."), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug35 = new DrugEntity(35, "Metolachlor", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug36 = new DrugEntity(36, "Oxyfluorfen", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug37 = new DrugEntity(37, "Propazine", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug38 = new DrugEntity(38, "Pendimethalin", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");
        DrugEntity drug39 = new DrugEntity(39, "Aldicarb sulfoxide", new ProducerEntity(8, "Bonageri Crop Science"), "Strains were previously selected for biocontrol ability from collections of >4000 bacteria. Strains 63-49 and 63-28 were tested on cucumber plants grown in rockwool in two replicatedPythium-inoculated trials conducted in British Columbia (B.C). Another inoculated, replicated trial was conducted in Quebec with all five strains. Cucumber yields (fruit number and weight) were measured over a ten-week harvest period. Strain 63-49 caused an early promotion of plant growth and increased cucumber yields at early harvests.");

        _drugRepository.saveAll(Arrays.asList(drug1, drug2, drug3, drug4, drug5, drug6, drug7, drug8, drug9, drug10, drug11, drug12, drug13, drug14, drug15, drug16, drug17, drug18, drug19, drug20, drug21, drug22, drug23, drug24, drug25, drug26, drug27, drug28, drug29, drug30, drug31, drug32, drug33, drug34, drug35, drug36, drug37, drug38, drug39));
    }

    private void initializeDiseases() {
        DiseaseEntity disease1 = new DiseaseEntity(1, "Blueberry___healthy", "Blueberry healthy");
        DiseaseEntity disease2 = new DiseaseEntity(2, "Apple___healthy", "Apple healthy");
        DiseaseEntity disease3 = new DiseaseEntity(3, "Apple___Black_rot", "Black rot");
        DiseaseEntity disease4 = new DiseaseEntity(4, "Tomato___Tomato_mosaic_virus", "Mosaic virus");
        DiseaseEntity disease5 = new DiseaseEntity(5, "Apple___Cedar_apple_rust", "Cedar rust");
        DiseaseEntity disease6 = new DiseaseEntity(6, "Apple___Apple_scab", "Scab");
        DiseaseEntity disease7 = new DiseaseEntity(7, "Pepper,_bell___healthy", "Bell healthy");
        DiseaseEntity disease8 = new DiseaseEntity(8, "Peach___healthy", "Peach healthy");
        DiseaseEntity disease9 = new DiseaseEntity(9, "Tomato___Late_blight", "Late blight");
        DiseaseEntity disease10 = new DiseaseEntity(10, "Tomato___Septoria_leaf_spot", "Septoria leaf spot");
        DiseaseEntity disease11 = new DiseaseEntity(11, "Soybean___healthy", "Soybean healthy");
        DiseaseEntity disease12 = new DiseaseEntity(12, "Potato___healthy", "Potato healthy");
        DiseaseEntity disease13 = new DiseaseEntity(13, "Tomato___Early_blight", "Early blight");
        DiseaseEntity disease14 = new DiseaseEntity(14, "Cherry_(including_sour)___healthy", "Sour healthy");
        DiseaseEntity disease15 = new DiseaseEntity(15, "Peach___Bacterial_spot", "Bacterial spot");
        DiseaseEntity disease16 = new DiseaseEntity(16, "Pepper,_bell___Bacterial_spot", "Bell Bacterial spot");
        DiseaseEntity disease17 = new DiseaseEntity(17, "Tomato___healthy", "Tomato healthy");
        DiseaseEntity disease18 = new DiseaseEntity(18, "Tomato___Spider_mites Two-spotted_spider_mite", "Spider mites Two spotted spider mite");
        DiseaseEntity disease19 = new DiseaseEntity(19, "Tomato___Target_Spot", "Target Spot");
        DiseaseEntity disease20 = new DiseaseEntity(20, "Raspberry___healthy", "Raspberry healthy");
        DiseaseEntity disease21 = new DiseaseEntity(21, "Strawberry___healthy", "Strawberry healthy");
        DiseaseEntity disease22 = new DiseaseEntity(22, "Orange___Haunglongbing_(Citrus_greening)", "Haunglongbing Citrus greening");
        DiseaseEntity disease23 = new DiseaseEntity(23, "Cherry_(including_sour)___Powdery_mildew", "Sour Powdery mildew");
        DiseaseEntity disease24 = new DiseaseEntity(24, "Potato___Late_blight", "Late blight");
        DiseaseEntity disease25 = new DiseaseEntity(25, "Tomato___Leaf_Mold", "Leaf Mold");
        DiseaseEntity disease26 = new DiseaseEntity(26, "Tomato___Tomato_Yellow_Leaf_Curl_Virus", "Yellow Leaf Curl Virus");
        DiseaseEntity disease27 = new DiseaseEntity(27, "Grape___Black_rot", "Black rot");
        DiseaseEntity disease28 = new DiseaseEntity(28, "Grape___healthy", "Grape healthy");
        DiseaseEntity disease29 = new DiseaseEntity(29, "Grape___Esca_(Black_Measles)", "Esca Black Measles");
        DiseaseEntity disease30 = new DiseaseEntity(30, "Strawberry___Leaf_scorch", "Leaf scorch");
        DiseaseEntity disease31 = new DiseaseEntity(31, "Corn_(maize)___Common_rust_", "Common rust");
        DiseaseEntity disease32 = new DiseaseEntity(32, "Potato___Early_blight", "Early blight");
        DiseaseEntity disease33 = new DiseaseEntity(33, "Corn_(maize)___Northern_Leaf_Blight", "Northern Leaf Blight");
        DiseaseEntity disease34 = new DiseaseEntity(34, "Tomato___Bacterial_spot", "Bacterial spot");
        DiseaseEntity disease35 = new DiseaseEntity(35, "Corn_(maize)___healthy", "Corn maize healthy");
        DiseaseEntity disease36 = new DiseaseEntity(36, "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot", "Cercospora leaf spot Gray leaf spot");
        DiseaseEntity disease37 = new DiseaseEntity(37, "Squash___Powdery_mildew", "Powdery mildew");
        DiseaseEntity disease38 = new DiseaseEntity(38, "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)", "Leaf blight Isariopsis Leaf Spot");

        _diseaseRepository.saveAll(Arrays.asList(disease1, disease2, disease3, disease4, disease5, disease6, disease7, disease8,
                disease9, disease10, disease11, disease12, disease13, disease14, disease15, disease16, disease17, disease18,
                disease19, disease20, disease21, disease22, disease23, disease24, disease25,disease26, disease27, disease28,
                disease29, disease30, disease31, disease32, disease33, disease34, disease35, disease36, disease37, disease38));
    }

    private void initializeProducers() {
        ProducerEntity producer1 = new ProducerEntity(1, "OAT Agrio");
        ProducerEntity producer2 = new ProducerEntity(2, "Syngenta");
        ProducerEntity producer3 = new ProducerEntity(3, "Bayer AG");
        ProducerEntity producer4 = new ProducerEntity(4, "DowDupont");
        ProducerEntity producer5 = new ProducerEntity(5, "BASF");
        ProducerEntity producer6 = new ProducerEntity(6, "Chaitra Agri Organics");
        ProducerEntity producer7 = new ProducerEntity(7, "Camson Bio Technologies Ltd.");
        ProducerEntity producer8 = new ProducerEntity(8, "Bonageri Crop Science");

        _producerRepository.saveAll(Arrays.asList(producer1, producer2, producer3, producer4, producer5, producer6, producer7, producer8));
    }
}
